name: 'Sync Issue Label to Project Field Action'
description: 'On issue create or label, tries to find a matching project item value and set it to the label' 
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: alert-circle
  color: green
inputs:
  owner-name:
    description: 'The owning organization/user for the project'
    type: string
    required: true
  project-id:
    description: 'The id of the project'
    type: number
    required: true
  field-name:
    description: 'The field to reference for the project'
    type: string
    required: true
  
  